# F.A.I.L. Kit GitHub Action
# Audit AI agent code for security and compliance issues
#
# This workflow runs on pull requests and:
# 1. Analyzes changed files for F.A.I.L. Kit issues
# 2. Compares against baseline (if exists)
# 3. Blocks merge if critical issues are found
# 4. Posts summary comment on PR

name: F.A.I.L. Kit Audit

on:
  pull_request:
    branches: [main, master, develop]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
  push:
    branches: [main, master]

permissions:
  contents: read
  pull-requests: write

jobs:
  audit:
    name: Agent Code Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install fail-audit CLI
        run: npm install -g fail-audit

      - name: Run F.A.I.L. Kit audit
        id: audit
        run: |
          npx fail-audit run \
            --format json \
            --output report.json \
            --include "**/*.{ts,tsx,js,jsx}" \
            --exclude "**/node_modules/**" \
            --exclude "**/*.test.*" \
            --exclude "**/*.spec.*"

      - name: Load baseline (if exists)
        id: baseline
        run: |
          if [ -f ".fail-kit/baseline.json" ]; then
            echo "baseline_exists=true" >> $GITHUB_OUTPUT
          else
            echo "baseline_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Compare to baseline
        if: steps.baseline.outputs.baseline_exists == 'true'
        id: compare
        run: |
          npx fail-audit compare \
            --current report.json \
            --baseline .fail-kit/baseline.json \
            --output comparison.json

      - name: Check for critical issues
        id: check
        run: |
          CRITICAL=$(jq '.summary.criticalCount // 0' report.json)
          HIGH=$(jq '.summary.highCount // 0' report.json)
          TOTAL=$(jq '.summary.totalIssues // 0' report.json)
          DECISION=$(jq -r '.summary.shipDecision // "SHIP"' report.json)

          echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
          echo "high=$HIGH" >> $GITHUB_OUTPUT
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          echo "decision=$DECISION" >> $GITHUB_OUTPUT

          if [ "$DECISION" = "BLOCK" ]; then
            echo "::error::F.A.I.L. Kit found $CRITICAL critical issue(s). Fix before merging."
            exit 1
          fi

      - name: Generate PR comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('report.json', 'utf8'));
            const summary = report.summary;

            let comparison = null;
            try {
              comparison = JSON.parse(fs.readFileSync('comparison.json', 'utf8'));
            } catch {}

            const icon = summary.shipDecision === 'SHIP' ? 'âœ…' : 
                        summary.shipDecision === 'BLOCK' ? 'ðŸš«' : 'âš ï¸';

            let body = `## ${icon} F.A.I.L. Kit Audit Report\n\n`;
            body += `| Metric | Count |\n|--------|-------|\n`;
            body += `| Critical | ${summary.criticalCount} |\n`;
            body += `| High | ${summary.highCount} |\n`;
            body += `| Medium | ${summary.mediumCount} |\n`;
            body += `| Low | ${summary.lowCount} |\n`;
            body += `| **Total** | **${summary.totalIssues}** |\n\n`;
            body += `**Decision:** ${summary.shipDecision}\n\n`;
            body += `**Reason:** ${summary.shipReason}\n\n`;

            if (comparison) {
              const delta = comparison.summary.delta;
              const deltaIcon = delta > 0 ? 'ðŸ“ˆ' : delta < 0 ? 'ðŸ“‰' : 'âž¡ï¸';
              body += `### Regression Analysis\n\n`;
              body += `${deltaIcon} ${delta > 0 ? '+' : ''}${delta} issues compared to baseline\n\n`;
              
              if (comparison.newIssues?.length > 0) {
                body += `**New Issues:**\n`;
                comparison.newIssues.slice(0, 5).forEach(issue => {
                  body += `- \`${issue.ruleId}\`: ${issue.message.substring(0, 60)}...\n`;
                });
                if (comparison.newIssues.length > 5) {
                  body += `- ... and ${comparison.newIssues.length - 5} more\n`;
                }
                body += '\n';
              }
            }

            body += `\n---\n*Generated by F.A.I.L. Kit v1.6.0*`;

            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const existingComment = comments.find(c => 
              c.user.login === 'github-actions[bot]' && 
              c.body.includes('F.A.I.L. Kit Audit Report')
            );

            if (existingComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              });
            }

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: fail-kit-report
          path: |
            report.json
            comparison.json
          retention-days: 30

      - name: Update baseline (main branch only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          mkdir -p .fail-kit
          cp report.json .fail-kit/baseline.json
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .fail-kit/baseline.json
          git diff --staged --quiet || git commit -m "chore: update F.A.I.L. Kit baseline"
          git push
