# F.A.I.L. Kit Audit - GitHub Actions Workflow
# 
# This workflow runs the F.A.I.L. Kit forensic audit on your AI agent.
# 
# Setup:
# 1. Copy this file to .github/workflows/fail-audit.yml
# 2. Set the AGENT_ENDPOINT secret in your repository settings
# 3. Optionally customize the audit level and other options
#
# For more information: https://fail-kit.dev/docs/ci-integration

name: F.A.I.L. Kit Audit

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      level:
        description: 'Audit level (smoke, interrogation, red-team)'
        required: false
        default: 'smoke'

env:
  # Default timeout in milliseconds
  FAIL_AUDIT_TIMEOUT: 30000

jobs:
  audit:
    name: Forensic Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install F.A.I.L. Kit
        run: npm install -g @fail-kit/cli
      
      # If you have a local agent to test, start it here
      # - name: Start Agent Server
      #   run: |
      #     npm install
      #     npm start &
      #     sleep 5  # Wait for server to start
      
      - name: Initialize Audit Config
        run: |
          fail-audit init --yes \
            --endpoint "${{ secrets.AGENT_ENDPOINT || 'http://localhost:8000/eval/run' }}" \
            --timeout ${{ env.FAIL_AUDIT_TIMEOUT }}
      
      - name: Run Smoke Test
        if: github.event_name == 'push' || github.event.inputs.level == 'smoke'
        run: fail-audit run --level smoke --format junit --output smoke-results.xml --ci
        continue-on-error: true
      
      - name: Run Interrogation (PR only)
        if: github.event_name == 'pull_request' || github.event.inputs.level == 'interrogation'
        run: fail-audit run --level interrogation --format junit --output interrogation-results.xml --ci
        continue-on-error: true
      
      - name: Run Full Red Team
        if: github.event.inputs.level == 'red-team'
        run: fail-audit run --format junit --output full-results.xml --ci
        continue-on-error: true
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fail-audit-results
          path: |
            *.xml
            audit-results/
      
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '*.xml'
          fail_on_failure: true
          include_passed: true
          detailed_summary: true
          check_name: 'F.A.I.L. Kit Audit Results'
      
      - name: Generate HTML Report
        if: failure()
        run: |
          for f in *.xml; do
            json_file="${f%.xml}.json"
            if [ -f "$json_file" ]; then
              fail-audit report "$json_file" --format html
            fi
          done
      
      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: fail-audit-html-reports
          path: '*.html'

  # Optional: Post results to PR as a comment
  comment:
    name: Post Results
    runs-on: ubuntu-latest
    needs: audit
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Download Results
        uses: actions/download-artifact@v4
        with:
          name: fail-audit-results
      
      - name: Generate Markdown Summary
        id: summary
        run: |
          # Find the most recent JSON results file
          RESULTS=$(ls -t audit-results/*.json 2>/dev/null | head -1 || echo "")
          
          if [ -n "$RESULTS" ] && [ -f "$RESULTS" ]; then
            fail-audit report "$RESULTS" --format markdown --output summary.md
            echo "has_results=true" >> $GITHUB_OUTPUT
          else
            echo "has_results=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Comment on PR
        if: steps.summary.outputs.has_results == 'true'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: summary.md
          comment_tag: fail-audit-results
