// Fix-ready output — generates flaw-fixes.md with actionable patches
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { AuditReport, TriageResult, Finding } from '../types/index.js';

function langFromFile(file: string): string {
  if (/\.tsx?$/.test(file)) return 'typescript';
  if (/\.jsx?$/.test(file)) return 'javascript';
  if (/\.py$/.test(file)) return 'python';
  if (/\.rb$/.test(file)) return 'ruby';
  if (/\.go$/.test(file)) return 'go';
  if (/\.java$/.test(file)) return 'java';
  if (/\.php$/.test(file)) return 'php';
  return '';
}

function renderFinding(f: Finding, index: number): string {
  const lines: string[] = [];
  const loc = `${f.location.file}${f.location.startLine ? `:${f.location.startLine}` : ''}`;
  const lang = langFromFile(f.location.file);

  lines.push(`### ${index}. ${f.title}`);
  lines.push(`**File:** \`${loc}\`  `);
  lines.push(`**Severity:** ${f.severity.toUpperCase()} | **Rule:** ${f.ruleId} | **Confidence:** ${f.confidence}`);
  lines.push('');

  if (f.codeSnippet) {
    lines.push('**Current code:**');
    lines.push(`\`\`\`${lang}`);
    lines.push(f.codeSnippet);
    lines.push('```');
    lines.push('');
  }

  lines.push(`**Why this matters:** ${f.impact}`);
  lines.push('');

  if (f.suggestedFix) {
    lines.push(`**What to do:** ${f.suggestedFix}`);
    lines.push('');
  }

  if (f.evidenceRefs && f.evidenceRefs.length > 0) {
    lines.push('**Related evidence:**');
    for (const ref of f.evidenceRefs) {
      lines.push(`- \`${ref}\``);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  return lines.join('\n');
}

export function exportFixes(report: AuditReport, triage: TriageResult, outputDir: string): string {
  const lines: string[] = [];
  const { summary } = report;

  lines.push(`# FLAW Fix Guide — ${report.project.name}`);
  lines.push(`> Generated ${report.generatedAt} | Score: ${summary.totalScore}/100 | ${summary.criticalCount} critical, ${summary.highCount} high, ${summary.mediumCount} medium`);
  lines.push('');

  // Top 3 callout
  if (triage.topThree.length > 0) {
    lines.push('## Fix These First');
    lines.push('');
    for (let i = 0; i < triage.topThree.length; i++) {
      const f = triage.topThree[i];
      const loc = `${f.location.file}${f.location.startLine ? `:${f.location.startLine}` : ''}`;
      lines.push(`${i + 1}. **${f.severity.toUpperCase()}:** ${f.title} — \`${loc}\``);
    }
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  let findingNum = 1;

  for (const group of triage.groups) {
    lines.push(`## Priority ${group.priority}: ${group.label}`);
    lines.push(`> ${group.rationale}`);
    lines.push('');

    for (const f of group.findings) {
      lines.push(renderFinding(f, findingNum++));
    }
  }

  // Remaining open findings not in triage (overflow)
  const triageFindingIds = new Set(triage.groups.flatMap(g => g.findings.map(f => f.id)));
  const remaining = report.findings.filter(f => f.status === 'open' && !triageFindingIds.has(f.id));

  if (remaining.length > 0) {
    lines.push('## Additional Findings');
    lines.push('');
    for (const f of remaining) {
      lines.push(renderFinding(f, findingNum++));
    }
  }

  lines.push('---');
  lines.push(`*Generated by FLAW — Flow Logic Audit Watch*`);

  const path = join(outputDir, 'flaw-fixes.md');
  writeFileSync(path, lines.join('\n'));
  return path;
}
